// Auto-generated by: npm run db:types
// Replace this file by running: npm run db:types (requires a linked Supabase project)

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          updated_at: string | null;
          avatar_url: string | null;
          chosen_name: string | null;
          last_name: string | null;
          phone_number: string | null;
          date_of_birth: string | null;
          created_at: string;
          gender: Database['public']['Enums']['gender'] | null;
          role: Database['public']['Enums']['user_role'];
          push_token: string | null;
        };
        Insert: {
          id: string;
          updated_at?: string | null;
          avatar_url?: string | null;
          chosen_name?: string | null;
          last_name?: string | null;
          phone_number?: string | null;
          date_of_birth?: string | null;
          created_at?: string;
          gender?: Database['public']['Enums']['gender'] | null;
          role?: Database['public']['Enums']['user_role'];
          push_token?: string | null;
        };
        Update: {
          id?: string;
          updated_at?: string | null;
          avatar_url?: string | null;
          chosen_name?: string | null;
          last_name?: string | null;
          phone_number?: string | null;
          date_of_birth?: string | null;
          created_at?: string;
          gender?: Database['public']['Enums']['gender'] | null;
          role?: Database['public']['Enums']['user_role'];
          push_token?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'profiles_id_fkey';
            columns: ['id'];
            isOneToOne: true;
            referencedRelation: 'users';
            referencedColumns: ['id'];
          },
        ];
      };
      dating_profiles: {
        Row: {
          id: string;
          user_id: string;
          bio: string | null;
          interested_gender: Database['public']['Enums']['gender'][];
          age_from: number;
          age_to: number | null;
          religion: Database['public']['Enums']['religion'];
          religious_preference: Database['public']['Enums']['religion'] | null;
          interests: Database['public']['Enums']['interest'][];
          city: Database['public']['Enums']['city'];
          is_active: boolean;
          created_at: string;
          updated_at: string;
          dating_status: Database['public']['Enums']['dating_status'];
        };
        Insert: {
          id?: string;
          user_id: string;
          bio?: string | null;
          interested_gender?: Database['public']['Enums']['gender'][];
          age_from: number;
          age_to?: number | null;
          religion: Database['public']['Enums']['religion'];
          religious_preference?: Database['public']['Enums']['religion'] | null;
          interests?: Database['public']['Enums']['interest'][];
          city: Database['public']['Enums']['city'];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          dating_status?: Database['public']['Enums']['dating_status'];
        };
        Update: {
          id?: string;
          user_id?: string;
          bio?: string | null;
          interested_gender?: Database['public']['Enums']['gender'][];
          age_from?: number;
          age_to?: number | null;
          religion?: Database['public']['Enums']['religion'];
          religious_preference?: Database['public']['Enums']['religion'] | null;
          interests?: Database['public']['Enums']['interest'][];
          city?: Database['public']['Enums']['city'];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          dating_status?: Database['public']['Enums']['dating_status'];
        };
        Relationships: [
          {
            foreignKeyName: 'dating_profiles_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      profile_photos: {
        Row: {
          id: string;
          dating_profile_id: string;
          suggester_id: string | null;
          storage_url: string;
          display_order: number;
          approved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          dating_profile_id: string;
          suggester_id?: string | null;
          storage_url: string;
          display_order: number;
          approved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          dating_profile_id?: string;
          suggester_id?: string | null;
          storage_url?: string;
          display_order?: number;
          approved_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'profile_photos_dating_profile_id_fkey';
            columns: ['dating_profile_id'];
            isOneToOne: false;
            referencedRelation: 'dating_profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'profile_photos_suggester_id_fkey';
            columns: ['suggester_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      prompt_templates: {
        Row: {
          id: string;
          question: string;
        };
        Insert: {
          id?: string;
          question: string;
        };
        Update: {
          id?: string;
          question?: string;
        };
        Relationships: [];
      };
      profile_prompts: {
        Row: {
          id: string;
          dating_profile_id: string;
          prompt_template_id: string;
          answer: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          dating_profile_id: string;
          prompt_template_id: string;
          answer: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          dating_profile_id?: string;
          prompt_template_id?: string;
          answer?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'profile_prompts_dating_profile_id_fkey';
            columns: ['dating_profile_id'];
            isOneToOne: false;
            referencedRelation: 'dating_profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'profile_prompts_prompt_template_id_fkey';
            columns: ['prompt_template_id'];
            isOneToOne: false;
            referencedRelation: 'prompt_templates';
            referencedColumns: ['id'];
          },
        ];
      };
      prompt_responses: {
        Row: {
          id: string;
          user_id: string;
          profile_prompt_id: string;
          message: string;
          is_approved: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          profile_prompt_id: string;
          message: string;
          is_approved?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          profile_prompt_id?: string;
          message?: string;
          is_approved?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'prompt_responses_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'prompt_responses_profile_prompt_id_fkey';
            columns: ['profile_prompt_id'];
            isOneToOne: false;
            referencedRelation: 'profile_prompts';
            referencedColumns: ['id'];
          },
        ];
      };
      contacts: {
        Row: {
          id: string;
          user_id: string;
          phone_number: string;
          wingperson_status: Database['public']['Enums']['wingperson_status'];
          created_at: string;
          winger_id: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          phone_number: string;
          wingperson_status: Database['public']['Enums']['wingperson_status'];
          created_at?: string;
          winger_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          phone_number?: string;
          wingperson_status?: Database['public']['Enums']['wingperson_status'];
          created_at?: string;
          winger_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'contacts_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      decisions: {
        Row: {
          id: string;
          actor_id: string;
          recipient_id: string;
          decision: Database['public']['Enums']['decision_type'] | null;
          suggested_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id: string;
          recipient_id: string;
          decision?: Database['public']['Enums']['decision_type'] | null;
          suggested_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string;
          recipient_id?: string;
          decision?: Database['public']['Enums']['decision_type'] | null;
          suggested_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'decisions_actor_id_fkey';
            columns: ['actor_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'decisions_recipient_id_fkey';
            columns: ['recipient_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'decisions_suggested_by_fkey';
            columns: ['suggested_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      matches: {
        Row: {
          id: string;
          user_a_id: string;
          user_b_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_a_id: string;
          user_b_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_a_id?: string;
          user_b_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'matches_user_a_id_fkey';
            columns: ['user_a_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'matches_user_b_id_fkey';
            columns: ['user_b_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      messages: {
        Row: {
          id: string;
          match_id: string;
          sender_id: string;
          body: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          match_id: string;
          sender_id: string;
          body: string;
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          match_id?: string;
          sender_id?: string;
          body?: string;
          is_read?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'messages_match_id_fkey';
            columns: ['match_id'];
            isOneToOne: false;
            referencedRelation: 'matches';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'messages_sender_id_fkey';
            columns: ['sender_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      get_discover_pool: {
        Args: {
          viewer_id: string;
          filter_winger_id?: string | null;
          page_size?: number;
          page_offset?: number;
        };
        Returns: Json[];
      };
      get_wing_pool: {
        Args: {
          winger_id: string;
          dater_id: string;
          page_size?: number;
          page_offset?: number;
        };
        Returns: Json[];
      };
    };
    Enums: {
      user_role: 'dater' | 'winger';
      dating_status: 'open' | 'break' | 'winging';
      gender: 'Male' | 'Female' | 'Non-Binary';
      religion:
        | 'Muslim'
        | 'Christian'
        | 'Jewish'
        | 'Hindu'
        | 'Buddhist'
        | 'Sikh'
        | 'Agnostic'
        | 'Atheist'
        | 'Other'
        | 'Prefer not to say';
      interest:
        | 'Travel'
        | 'Fitness'
        | 'Cooking'
        | 'Music'
        | 'Art'
        | 'Movies'
        | 'Books'
        | 'Gaming'
        | 'Outdoors'
        | 'Sports'
        | 'Technology'
        | 'Fashion'
        | 'Food'
        | 'Photography'
        | 'Dance'
        | 'Volunteering';
      city: 'London' | 'Manchester' | 'Birmingham' | 'Leeds' | 'Glasgow';
      wingperson_status: 'invited' | 'active' | 'removed';
      decision_type: 'approved' | 'declined';
    };
    CompositeTypes: Record<string, never>;
  };
};
